### PR TITLE
don't import normalize from Base

### PR DESCRIPTION
**Pull request by tkelman**
all your methods here are on Base types, this is complete type piracy if imported

### CODE REVIEW

**Comment by sglyon** [comment]
@albop what do you think we should do here?

@tkelman is right that we shouldn't be adding methods to a function from Base for types defined in Base. 

If we merge this as is and don't extend the method from Base, then I think it becomes more difficult to use our version of `normalize` and the one from Base. Uses of it need be qualified with the module name:

```
julia> using Dolang
INFO: Recompiling stale cache file /Users/sglyon/.julia/lib/v0.6/Dolang.ji for module Dolang.

julia> normalize(:(x(0)))
WARNING: both Dolang and Base export "normalize"; uses of it in module Main must be qualified
ERROR: UndefVarError: normalize not defined

julia> Dolang.normalize(:(x(0)))
:_x__0_
```

An alternative would be to rename it. I'm not 100% attached to the name. We could go for `lower` or `standardize`. 

Thoughts?

**Comment by albop** [comment]
Well, apart from starting an uncertain fight about what the
normalize method in Base should be about, I guess, it makes sense to
rename. Is standardize taken ?
Thank you @tkelman for spotting this.

**Comment by sglyon** [comment]
standardize is available

**Comment by albop** [comment]
Let's go for that one then

**Comment by albop** [comment]
But, wait a sec, there is no urgency in doing that, right. If we follow the suggestion of not importing from base, the damage is very limited for now.

**Comment by sglyon** [comment]
The snippet I showed above was what happens when we don't import from base.

In that case we create a new _function _ (not method)`Dolang.normalize` that coexists with `Base.LinAlg.normalize`. However after `using Dolang` In order to use either of those functions you need to prefix with the module name. 

The damage is needing the `Dolang.` prefix

**Comment by albop** [comment]
Not a big deal. People who will use the functions are supposed to be smart
enough for that...

**Comment by sglyon** [comment]
Haha k sounds good to me.

Thanks again @tkelman

**Pull request merged**
