### PR TITLE
BUG: fix up compiler.jl

### PR DESCRIPTION
**Pull request by sglyon**
Ok I couldn't leave this with one test suite commented out....

Fixed compiler.jl and associated tests

### CODE REVIEW

**Comment by sglyon** [comment]
OK so this issue was subtle.

In the generated functions I create a sparse array by calling `sparse`

If someone hasn't done `SparseArrays` in _in the module where the intend to use the generated code_ you will get an error saying that `sparse` is undefined.

To fix it, I just load SparseArrays in runtests.jl, but this might be confusing for users... Thoughts

**Comment by albop** [comment]
Why isn't it the same for any function we use in the generated code ?

**Comment by albop** [comment]
What's wrong with adding import SparseArrays:sparse to the code we generate if needed ?

**Comment by sglyon** [comment]
We generate function bodies and we cannot import functions in a body function.

We could do `using SparseArrays: sparse` after the end of the module  so it is loaded wherever `using Dolang` is loaded. That would help, but might not solve everything

**Comment by albop** [comment]
I thought we were generating a code block with several functions. If so the import statement could be prepended at the beginning of the code block.
Anyway, we have the same issue with other helper functions from Dolang, like _getsize, and alike that we use in the generated functions. Evaluating their code works only if they have been exported from Dolang in the right module.
So let's do nothing here, and create an issue to remember us to document it, and to discuss whether a fix is desirable or not. 
In the meantime, I"m merging... Thanks again

**Comment by sglyon** [comment]
Ahh good point. We may be able to add that to the block of code that We generate. Good idea!

**Pull request merged**
